//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFill.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestImportEntities1 : DbContext
    {
        public TestImportEntities1()
            : base("name=TestImportEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IDMaterial> IDMaterial { get; set; }
        public virtual DbSet<IDNameProduct> IDNameProduct { get; set; }
        public virtual DbSet<IDTypeProduct> IDTypeProduct { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductImport> ProductImport { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
