//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImport
    {
        public int Article { get; set; }
        public decimal Minimum { get; set; }
        public string image { get; set; }
        public int IDTypeProduct { get; set; }
        public int Number { get; set; }
        public int Production { get; set; }
    
        public virtual IDTypeProduct IDTypeProduct1 { get; set; }
    }
}
